### ISSUE TITLE
Fix SourceKit crashes

### ISSUE THREAD

**Issue by jbrennan** [Khan/OhaiPrototope#5]
Seriously whoever fixes this will get so many celebration gifs.

**Comment by andymatuschak** [comment]
I knowwww. :(

I spent a while trying but couldn’t isolate what was making it angry. I think it has something to do with Pop’s header not being found by SourceKit (like it’s not respecting the header search paths)? I guess I think that because sometimes Xcode will actually show an error about that header being missing in the bridging header.

**Comment by nsfmc** [comment]
man, @jbrennan you got my hopes up when i saw this in my inbox that this was a pull request not an issue.

**Comment by jbrennan** [comment]
@nsfmc sorry :(

I figured we’d get the word out in case any intrepid outside developers happen to know the cure!

**Comment by jbrennan** [comment]
Seems to be fixed by Xcode 6.3 huzza! :tada:
